resque_app/config/routes.rb
ResqueApp::Application.routes.draw do
  resources :snippets

  root :to => 'snippets#new'

end

resque_app/app/models/snippet.rb
class Snippet < ActiveRecord::Base

  validates :name, :presence => true
  validates :plain_code, :presence => true

end

resque_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

resque_app/app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController

  def show
    @snippet = Snippet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  def new
    @snippet = Snippet.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  def create
    @snippet = Snippet.new(params[:snippet])
    if @snippet.save
      Resque.enqueue(::SnippetHighlighter, @snippet.id)
      redirect_to @snippet, :notice => "Successfully created snippet."
    else
      render 'new'
    end
  end

end

resque_app/app/helpers/application_helper.rb
module ApplicationHelper
end

resque_app/app/helpers/snippets_helper.rb
module SnippetsHelper
end

resque_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ResqueApp</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

resque_app/app/views/snippets/_form.html.erb
<%= form_for(@snippet) do |f| %>
  <% if @snippet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@snippet.errors.count, "error") %> prohibited this snippet from being saved:</h2>

      <ul>
      <% @snippet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :language %><br />
    <%= f.select :language, options_for_select([["Ruby", "ruby"], ["Python", "python"], ["JavaScript", "javascript"], ["CSS", "css"]]) %>
  </div>
  <div class="field">
    <%= f.label :plain_code %><br />
    <%= f.text_area :plain_code, :rows => 14, :cols => 50 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

resque_app/app/views/snippets/new.html.erb
<h1>New snippet</h1>

<%= render 'form' %>

resque_app/app/views/snippets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @snippet.name %>
</p>

<p>
  <b>Language:</b>
  <%= @snippet.language %>
</p>

<div class="code_block">
  <b>Source code:</b>
  <% if @snippet.highlighted_code.present? %>
    <%= raw @snippet.highlighted_code %>
  <% else %>
    <pre><%= @snippet.plain_code %></pre>
  <% end %>
</div>


<%= link_to 'Get another one', new_snippet_path %>